POST http://localhost:5050/signUp
Content-Type: application/json

{
  "email": "test3@test.com",
  "nickname": "test",
  "password": "1234"
}

###
POST http://localhost:5050/api/login
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "1234"
}

###
POST http://localhost:5050/api/token/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWMwMDk4a2owMDAwdHg2a2dqNnQzOHl6IiwiaWF0IjoxNzUwMzg1MTU1LCJleHAiOjE3NTAzODg3NTV9.fjiyxuhIxR8Y8357qGloiwpbUfy57Loz7FVwD_QfkNU

###
POST http://localhost:5050/api/logout
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWMwMDk4a2owMDAwdHg2a2dqNnQzOHl6IiwiaWF0IjoxNzUwMzg1MTY2LCJleHAiOjE3NTAzODg3NjZ9.HEE9GfYV9dNekCLz0dkWKfzGecrz3V5Xudp7Bdq0DRA