POST http://localhost:5050/signUp
Content-Type: application/json

{
  "email": "test3@test.com",
  "nickname": "test",
  "password": "1234"
}

###
POST http://localhost:5050/api/login
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "1234"
}

###
POST http://localhost:5050/api/token/refresh
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWMwYjhpbHUwMDAxdHhka2JzdHNpOXl2IiwiaWF0IjoxNzUwMzI2NzE5LCJleHAiOjE3NTE1MzYzMTl9.FIIzITzgvdpzOhln-D4ErFGQL8nD4bFjcWAxvZuAbS8